#!/bin/bash

# @script makes a new file, makes it executable, then opens it in vim.
# based on script taken from rhowaldt on the #! fora, and improved by xaos52

_LOCATION="$HOME/scripts"
_PATH=""
_TOUCH="touch"
_CHMOD="chmod"
# If there is a $EDITOR variable already defined, we might as well use that
# Otherwise, you can uncomment this line
#EDITOR=gedit

# if there is no EDITOR variable set, then see if vim or nano is available
# if neither is, then we look for /etc/alternatives/editor
# if this is not there either, then complain to the user
if ! which $EDITOR >/dev/null; then
  if which nano >/dev/null; then
    EDITOR=nano
  else
    if which vim >/dev/null; then
      EDITOR=vim
    else
      if [ -f /etc/alternatives/editor ]; then
        EDITOR="readlink /etc/alternatives/editor"
      else
        echo "Please define the $EDITOR variable"
        echo "@script does not know which editor to use"
        exit 1
      fi
    fi
  fi
fi


if [ $# -lt 1 ]; then
    echo "Use '@script <scriptname> [<location>]'."
    exit
fi

if [ $2 ]; then
    if [ ! -d "$2" ]; then
        echo "Location does not exist."
        exit
    else
        _LOCATION="$2"
    fi
fi

_PATH="$_LOCATION/$1"
$_TOUCH $_PATH
$_CHMOD +x $_PATH
$EDITOR $_PATH
