#! /bin/sh

# Check to see whether a word is in a given word list.

WORDLIST=/usr/share/dict/words
# this should be on most Unix systems. It is not, however, the
# complete scrabble word list; if you have a better word list
# available on your system, you should prefer that.
SEARCH='grep -w'

check ()
{
    # a neat trick from the Useless Use of Cat awards page.  we are
    # running grep here for its exit code.  if there is a match it will
    # return exit 0 and the if loop will succeed.  otherwise it will
    # return exit 1 and the loop will fail.  redirection is to /dev/null
    # so as not to pollute stdout.
    if $SEARCH $1 $WORDLIST > /dev/null; then
        # colour 'VALID' green
        echo "\033[32;1mVALID"
    else
        # colour 'INVALID' red
        echo "\033[31;1mINVALID"
    fi
}

if [ $# -lt 1 ]; then
    echo "Error: Not enough arguments."
    echo "Please enter a word to check."
    exit 1
fi

check $1

exit 0
