#!/usr/bin/env python

# Create a starting position for Fischerrandom Chess.

import random, sys

try:
    output = int(sys.argv[1])
except IndexError:
    output = 1

def pos_gen():
    pawns = "pppppppp/"
    spaces = "8/8/8/8/"
    start = " w KQkq - 0 1"
    fen = ""
    pieces = ""

    squares = [1,2,3,4,5,6,7,8]
    bb = random.randrange(1,8,2)
    bw = random.randrange(2,9,2)
    squares.remove(bb)
    squares.remove(bw)
    q = random.choice(squares)
    squares.remove(q)
    n1 = random.choice(squares)
    squares.remove(n1)
    n2 = random.choice(squares)
    squares.remove(n2)
    bb = str(bb)+"b"
    bw = str(bw)+"b"
    n1 = str(n1)+"n"
    n2 = str(n2)+"n"
    q = str(q)+"q"
    r1 = str(squares[0])+"r"
    k = str(squares[1])+"k"
    r2 = str(squares[2])+"r"

    start_positions = [bb, bw, q, n1, n2, k, r1, r2]

    start_positions.sort()

    for piece in start_positions:
        pieces += piece[-1]

    fen = pieces + "/" + pawns + spaces + pawns.upper() + pieces.upper() + start

    print(fen)

for i in range(output):
    pos_gen()
