#!/bin/bash

# Sanitize filenames in a directory.

# A replacement for fclean and fclean_dir.  Searches recursively
# through directory for files with un-unixy names, and makes them
# cleaner.

# REPLACES:

# capitals with lowercase.
# spaces with underscores.

# REMOVES:

# Any non-word characters [A-Za-z0-9_-]

# Leaves a log file, detailing the name changes

# WARNING: Be careful when using this on your home directory.  Cleaner
# may change the names of configuration files without asking
# permission.  For instance, .Xauthority and .Xresources would be
# renamed.

downcase () {
    find . -depth -name "*[A-Z ]*" -exec rename -v 'tr/[A-Z][ ]/[a-z][_]/' '{}' > .cleaner.log \;
}

unpunctuate () {
    find . -depth -name "*[\!\?\,\[\]\{\}\(\)\'\"]*" -exec rename -v 's/[^\w\.\/]//g' '{}' > .cleaner.log \;
}

downcase && unpunctuate

exit 0
