#!/usr/bin/env python
# unit conversion script: useful for bakers, perhaps?
# ToDo: add error checking: what if someone puts in non-numeric characters?

import gtk

calculator = gtk.Window()

gramsoz = gtk.Button("Grams to Ounces")
ozgrams = gtk.Button("Ounces to Grams")
mlpt = gtk.Button("Millilitres to Pints")
ptml = gtk.Button("Pints to Millilitres")
CtoF = gtk.Button("Celsius to Fahrenheit")
FtoC = gtk.Button("Fahrenheit to Celsius")
cupsoz = gtk.Button("Cups to Ounces")
quit = gtk.Button("Quit")

vbox = gtk.VBox()
weightbox = gtk.HBox()
volumebox = gtk.HBox()
tempbox = gtk.HBox()
text = gtk.Entry()

calculator.add(vbox)

weightbox.pack_start(gramsoz)
weightbox.pack_start(ozgrams)
weightbox.pack_start(cupsoz)
volumebox.pack_start(mlpt)
volumebox.pack_start(ptml)
tempbox.pack_start(CtoF)
tempbox.pack_start(FtoC)
vbox.pack_start(text)
vbox.pack_start(weightbox)
vbox.pack_start(volumebox)
vbox.pack_start(tempbox)
vbox.pack_start(quit)

def output(out):
  returns = str(out)
  text.set_text(returns)

def ozgramsclicked(btn):
  usrinput = float(text.get_text())
  result = usrinput*28.35
  output(result)

def gramsozclicked(btn):
  usrinput = float(text.get_text())
  result = usrinput*0.03527
  output(result)

def mlptclicked(btn):
  usrinput = float(text.get_text())
  result = usrinput*0.00176
  output(result)

def ptmlclicked(btn):
  usrinput = float(text.get_text())
  result = usrinput*568.3
  output(result)

def celsiusfahren(btn):
  usrinput = float(text.get_text())
  result = usrinput * 9.0 / 5.0 + 32
  output(result)

def fahrencelsius(btn):
  usrinput = float(text.get_text())
  result = (usrinput - 32) * 5.0 / 9.0
  output(result)

def cupsozclicked(btn):
  usrinput = float(text.get_text())
  result = usrinput * 8
  output(result)

def quitclicked(btn):
  gtk.main_quit()

gramsoz.connect("clicked", gramsozclicked)
ozgrams.connect("clicked", ozgramsclicked)
mlpt.connect("clicked", mlptclicked)
ptml.connect("clicked", ptmlclicked)
CtoF.connect("clicked", celsiusfahren)
FtoC.connect("clicked", fahrencelsius)
cupsoz.connect("clicked", cupsozclicked)
quit.connect("clicked", quitclicked)

calculator.show_all()
gtk.main()
