#!/bin/bash
# heavily rewritten 04-02-2014 to use getopts to handle command-line flags
# still buggy and error prone: in particular, the -f and -i flags do not work properly

tao=$HOME/media/todo
range=($(echo {1..100}))
SUGGEST=0
SEARCH='grep'

# shuffle function based on Knufth-Fisher-Yayes shuffle algorithm
# http://mywiki.wooledge.org/BashFAQ/026 thank you!
# takes an array as input through 'shuffle ARRAY[@]', outputs arr[@]
shuffle() {
   local i tmp size max rand
   arr=("${!1}") # retrieve array from $1
   # $RANDOM % (i+1) is biased because of the limited range of $RANDOM
   # Compensate by using a range which is a multiple of the array size.
   size=${#arr[*]}
   max=$(( 32768 / size * size ))

   for ((i=size-1; i>0; i--)); do
      while (( (rand=$RANDOM) >= max )); do :; done
      rand=$(( rand % (i+1) ))
      tmp=${arr[i]} arr[i]=${arr[rand]} arr[rand]=$tmp
   done
}

# Valid options:
# -a (all); -c (count) -h (usage options) -i (case insensitive) -f (word parts accepted) -s (search) -v (version)
while getopts ac:fhis:v opt; do
  case $opt in
    a)
      cat $tao
      exit 0
      ;;
    i)
      SEARCH='$SEARCH -i'
      ;;
    f)
      SEARCH='$SEARCH -w'
      ;;
    c)
      $SEARCH -c $OPTARG $tao
      exit 0;
      ;;
    h)
      echo "cosmo: bringing hilarious sex tips to your command line"
      echo "Usage: cosmo [OPTION] [SEARCH TERM]"
      echo "       cosmo [1-100]"
      echo "       cosmo -a"
      echo "       cosmo -h"
      echo "cosmo returns a random sex suggestion taken from a list from the "
      echo "Cosmopolitan UK website."
      echo ""
      echo "OPTIONS:"
      echo "-s  returns a random suggestion containing the search term given."
      echo "-a  returns all suggestions containing the search term given."
      echo "-c  returns a count of how many suggestions contain a search term."
      echo "-f  do not limit searches to exact matches."
      echo "    cosmo is by default case-sensitive and matches only exact words."
      echo "    Thus, 'cosmo the' will not return suggestions containing 'then' or 'there'."
      echo "    'cosmo -f' turns this option off."
      echo "-i  make matches case insensitive."
      exit 0
      ;;
    s)
      $SEARCH $OPTARG $tao
      exit 0;
      ;;
    v)
      echo "cosmo v.2.0"
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit 1;
      ;;
    :)
      echo "-$OPTARG requires an argument"
  esac
done

if [[ $# -eq 0 ]]; then
   shuffle range[@] && SUGGEST=${arr[1]}
fi

if [[ $# -eq 1 ]]; then
   for n in ${range[@]}; do
      [[ $1 -eq $n ]] && SUGGEST=$1
   done
   if [[ $SUGGEST -eq 0 ]]; then
      echo "Cosmo only has a limited number of suggestions."
      echo "If this is not enough for you, there is always toilet-paper bondage."
      exit 1
   fi
fi

exit 0
