#! /usr/bin/env python
# WARNING: All these procedures are INSECURE.
# They have all been broken for hundreds of years.
# In the event that you wish to secure data properly, please use RSA, PGP, or another encryption standard.
# The cryptograms in this module are toys, and are not a replacement for proper data security.

import sys

text = open(sys.argv[1])

#Performs a Caesar shift on a string by n places.
def caesar_shift (string, shift):
  d = {}
  for c in (65, 97):
    for i in range(26):
      d[chr(i+c)] = chr((i+shift) % 26 + c)
  print "".join([d.get(c, c) for c in string])

#INCOMPLETE!!!
def vignere (string, key):
  #convert key into integers mapping a::0, b::1 etc
  d = {}
  for c in (65, 97):
    for i in range(26):
      d[chr(i+c)] = chr((i+shift) % 26 + c)
  print "".join([d.get(c, c) for c in string])

#Performs a railfence cipher on a string.
def railfence(string):
  plaintext = list(string)
  a = len(plaintext)
  for i in range(0, a, 2):
    print plaintext[i]
  for j in range (1, a, 2):
    print plaintext[j]
