#!/bin/sh

# Power management for dmenu

COMMANDS="
suspend\n
poweroff\n
reboot\n
hibernate\n
hybrid-sleep\n
halt\n
"

command=$(echo $COMMANDS | dmenu -i)
[ "$command" = "" ] && exit 1
sudo systemctl $command && exit 0
