#!/bin/bash

# Clean up a file-name.

# Originally by paramthegreat on the Arch fora.

# Replaces spaces with underscores.
# Removes unwanted characters.
# Makes everything lowercase.
# Replaces hyphens after numbers with underscores.

ls | while read -r FILE

     do
         mv -v -- "$FILE" `echo $FILE | tr ' ' '_' | tr -d '[{}(),\!]?*|' | tr -d "\'" | tr '[A-Z]' '[a-z]' | sed 's/\([0-9][0-9]\)-/\1_/' | sed s/_-_/_/`
     done

exit 0
