#!/bin/bash
# obtained from rhowadlt on #! fora

traverse() {
   local d startdir
   cd -- "$1" || exit 1 
   if [[ $(find -type d -empty) != "." ]]; then
      for d in *; do
         [ -d "$d" ] && traverse "$d"
         fclean
      done
   fi
   cd .. || exit 1
}

traverse .
