#!/bin/bash
# obtained from paramthegreat @ Arch forums
# replaces spaces with underscores
# removes unwanted characters
# makes everything lowercase
# replaces hyphen after numbers with underscore

ls | while read -r FILE
do
    mv -v -- "$FILE" `echo $FILE | tr ' ' '_' | tr -d '[{}(),\!]' | tr -d "\'" | tr '[A-Z]' '[a-z]' | sed 's/\([0-9][0-9]\)-/\1_/'`
done
exit 0
