#! /bin/sh

# Frequency analyse a text file.

TEMPFILE=$HOME/tmp

if [ $# -ne 1 ]; then
    echo "Error: wrong number of arguments"
    echo "Syntax: `fran $filename`"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Filename does not exist."
    exit 1
else
    cat $1 > $TEMPFILE
fi

sed 's/./&\n/g' $TEMPFILE | sort | uniq -c | sort -nr

rm $TEMPFILE

exit 0
