#! /bin/sh

# Frequency analyse a text file.

TEMPFILE=$HOME/tmp

if [ $# -ne 1 ]; then
    echo "Error: wrong number of arguments"
    echo "Syntax: `fran $filename`"
    exit 1
fi

if [ $1 ]; then
    if [ ! -f "$1" ]; then
        echo "Filename does not exist."
        exit
    else
        cat $1 > $TEMPFILE
    fi
fi

sed 's/./&\n/g' $TEMPFILE | sort | uniq -c | sort -nr

rm $TEMPFILE

exit 0
