#! /bin/sh
# frequency analysis tool

TEMPFILE=$HOME/tmp

if [ $# -lt 1 ]; then
    echo "Use 'fran <filename>'."
    exit
fi

if [ $1 ]; then
    if [ ! -f "$1" ]; then
        echo "Filename does not exist."
        exit
    else
        cat $1 > $TEMPFILE
    fi
fi

sed 's/./&\n/g' $TEMPFILE | sort | uniq -c | sort -nr

rm $TEMPFILE
