#!/bin/bash
# count how many lines of code have been written in a language,
# and tell a user what 'level' ze is on

DIRECTORY=$HOME/scripts

for i in $DIRECTORY/*; do
  if [[ file -ib $i == "text/x-python*" ]]; then
    wc -l
    #something
  fi
  if [[ file -ib $i == "text/x-shellscript*" ]]; then
  fi
done

# count lines of each file
# can use `wc -l` -- but must also remove whitespace and commented lines...
