#!/bin/bash

# Check if a file's md5sum matches a string.

# Usage: mdcheck $filename $md5string

# Based on a script by milo64 from the Arch Fora.

check () {
    if [ "$(md5sum $1 | cut -d ' ' -f 1)" = "$2" ]; then
        echo "Checksum matched."
        exit 0
    else
        echo "Checksum not matched."
        exit 1
    fi
}

if [ $# -ne 2 ]; then
    echo "ERROR: mdcheck requires two arguments."
fi

if [ -a "$1" ]; then
    check $1 $2
else
    echo "ERR: '$1' No such file."
    exit 1;
fi
