#! /usr/bin/env python

import gtk
import subprocess
import sys

window = gtk.Window()
vbox = gtk.VBox()
hbox = gtk.HBox()
wordbox = gtk.Entry()
check = gtk.Button("Check")
reply = gtk.Label()
window.add(vbox)
vbox.pack_start(hbox)
hbox.pack_start(wordbox)
hbox.pack_start(check)

def checkclicked(btn):
  word = wordbox.get_text()
  subprocess.call(['/home/joe/scripts/allowed', '-c', word])
  reply.set_text()

check.connect("clicked", checkclicked)

window.show_all()
gtk.main()
