#!/bin/sh

DATAFILE=$HOME/books/my_library.gcs

# gives a list of tag opening lines
grep -n <tags> $DATAFILE | awk -F : '{ print $1 }' > tmp1
grep -n </tags> $DATAFILE | awk -F : '{ print $1 }' > tmp2
paste tmp1 tmp2 > tmp3

# stuff

# cleanup tmp files
rm tmp1 tmp2 tmp3
