#!/bin/sh
#script to add tasks
#is there a file called ~/.tasks?
if [! -f ~/.tasks]; then
	touch ~/.tasks;
fi

echo task?
read TASK
echo urgent? 1/0
read INPUT
if [ $INPUT=1 ]; then
  $URGENCY='!'
echo complete by? ddmmyy
read TIME
$TASK $URGENCY $TIME >> ~/.tasks

