#!/bin/bash

# default functionality informs user that her tea is ready after three minutes
if [ $# -lt 1 ]; then
  sleep 180
fi

# allow a custom time length (in seconds)
if [ $# = 1 ]; then
  sleep $1
fi

notify-send "Tea's up!"
aplay ~/misc/chime.wav
