#! /usr/bin/env python
# A Tiny EDITor

from sys import argv
from os.path import exists

script, filename = argv

#if file exists, print contents of file to stdout
if exists(filename):
  f = open(filename)
  f.read()
  f.close
  f = open(filename, 'a')
  append = raw_input()
  f.write(append)
  f.write("\n")
  f.close
#if file doesn't exist, touch file and write single line to file
else:
  print "creating new file %r" % filename
f = open(filename, 'w')
append = raw_input()
f.write(append)
f.write("\n")
f.close
