#!/bin/bash

while getopts ":a" opt; do #while there are still opt flags, loop
  case $opt in
    a)
      echo "-a was triggered" 
      ;;
    \?)
      echo "invalid option: -$OPTARG" 
      exit 1 # when there is an error, exits with status 1
      ;;
  esac
done
