#!/bin/bash

# Set wallpaper at random to one in the defined directory.

DIR=$HOME/images/desktops
SET="hsetroot -full"

if [ $# -ne $1 ]; then
    echo "ERROR: Wrong number of arguments."
    echo "Usage: `wallpaper $directory`"
    exit 1
fi

if [ -d "$1" ]; then
    DIR=$1
else
    echo "WARNING: " $1 " is not a directory"
    echo "Continuing with " $DIR
fi

find $DIR -type f -print | shuf -n 1 | xargs $SET

exit 0
