#!/bin/bash
# sets wallpaper at random to one in the defined directory

DIR=$HOME/images/desktops
SET="hsetroot -full"

if [ $1 ]; then
  if [ -d "$1" ]; then
    DIR=$1
  else
    echo $1 "is not a directory"
  fi
fi

find $DIR -type f -print | shuf -n 1 | xargs $SET
