#!/bin/bash
# wordcounter

TEMPFILE=/home/joe/tempfile

if [ $# -lt 1 ]; then
    echo "Use 'wordcount <filename>'."
    exit
fi
if [ $1 ]; then
    if [ ! -f "$1" ]; then
        echo "Filename does not exist."
        exit
    else
        FILENAME="$1"
    fi
fi

cat $FILENAME > $TEMPFILE
sed 's/\.//g;s/\(.*\)/\L\1/;s/\ /\n/g' $TEMPFILE | sort | uniq -c | sort -nr | head -n 20

rm $TEMPFILE
