#!/bin/sh

# Return the 20 most-used words in a text file, and their number of uses.

TEMPFILE=$HOME/tempfile

if [ $# -lt 1 ]; then
    echo "Error: Not enough arguments."
    echo "Syntax: `wordcount $filename`"
    exit 1
fi

if [ $1 ]; then
    if [ ! -f "$1" ]; then
        echo "Error: `$1` does not exist."
        exit 1
    else
        FILENAME="$1"
    fi
fi

cat $FILENAME > $TEMPFILE

sed '
# replace every character except for those in the set [A-Za-z0-9 ]
# with nothing.
s/[^a-zA-Z0-9 ]//g
# replace every space with a new line
s/\ /\n/g' $TEMPFILE \
    | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep "[a-z]" - | sort -nr |  head -n 20

rm $TEMPFILE

exit 0
