#!/usr/bin/env python
# Card decks module

import random

hearts = ["AH","2H","3H","4H","5H","6H","7H","8H","9H","10H","JH","QH","KH"]
clubs = ["AC","2C","3C","4C","5C","6C","7C","8C","9C","10C","JC","QC","KC"]
diamonds = ["AD","2D","3D","4D","5D","6D","7D","8D","9D","10D","JD","QD","KD"]
spades = ["AS","2S","3S","4S","5S","6S","7S","8S","9S","10S","JS","QS","KS"]
jokers = ["RedJoker", "BlackJoker"]

# define what cards are in the deck
# currently assumes that a deck is a single pack of cards
deck = [hearts, clubs, diamonds, spades]

def deal(cards, players):
  random.shuffle(deck)
  for i in (1, cards):
    card = deck.pop()


