#!/usr/bin/env python
# a script which plays hangman with you
import random

dict_words = "/usr/share/dict/words"

# build a list of words from /usr/share/dict/words
# for lines in dict_words
# ignore if word != lowercase word
# ignore if word <4 or >15 letters
# else:
#   words.append word

def choose ():
  choice = random.choice(words)
  #count letters in word
  print "I'm thinking of a word with", letters, "letters"

