#! env /usr/bin/python

#A program which keeps track of tasks and deadlines
#to do: write a menu-driven interface for the program; write the code for writing tasks to file; write tasksdue & remtask code.

import datetime

def addtask(x):
  name = x
  description = str(raw_input("Description?"))
  dueday = int(raw_input("Day due?"))
  duemonth = int(raw_input("Month due?"))
  dueyear =  int(raw_input("Year due?"))
  due = datetime.date(dueyear, duemonth, dueday)
  importance = str(raw_input("Mark as important (y/n)?")
  #write task to file containing list of tasks.

def tasksdue():
  #read tasks file
  #remove any timed out tasks
  #print remaining tasks due in next fortnight, + those marked as important.

def remtask():
  #mark a task in the list as complete i.e. remove from list.
