#!/bin/sh

# calculator based on bc and dmenu

# Based on djp's script on the Arch forums.  Made sh compatible, and
# uses bc instead of python for greater power.

if [ -f "$HOME/.config/dmenurc" ]; then
    . $HOME/.config/dmenurc
else
	DMENU="dmenu -i -l 20"
fi

hist="$(xsel -o)"

(echo "$hist" | bc -l 2>/dev/null) || hist=False

calc=$(echo $hist | $DMENU -l 20 -p Calculate:)

prev="$calc"

while true; do
    case $calc in
        ""|"exit")
            break
            ;;
        *)
            prev="$calc"
            hist="$prev\n$hist"
            calc=$(echo "$calc; print \"\n$hist\"" | bc -l 2>/dev/null\
                          | $DMENU -l 20 -p "Calculate:")
            ;;
    esac
done

echo "$prev" | bc -l 2>/dev/null | xsel -i
