#!/bin/bash

# based on the mpdmenu script found at
# https://github.com/k00mi/mpdmenu

# maintained by Joe Kitchen at https://github.com/joek295/scripts

MPC="mpc --quiet -p ${1:-6600}"

# max height for vertical menu
height=20

DMENU() {
    # Vertical menu if $3 is given
    echo -e "$1" | dmenu -i -b -p "$2" ${3:+"-l" "$3"}
}

# Show name and title together: all of my tracks have one but not the
# other, and there isn't any consistency.  One of these days I shall
# sit down and fix this.  My conkyrc uses the same kludge.
get_playlist() {
    $MPC -f "%position% - %artist% - %album% - %name%%title%" playlist
}

select_from() {
    DMENU "$1" "Select $2" $height
}

add() {
    all="[ALL]"

    local artist=$(select_from "$($MPC list Artist)\n$all" "artist")

    if [ "$artist" = "$all" ]; then
        $MPC listall | $MPC add;
    elif [ -n "$artist" ]; then
        local albums=$($MPC list Album Artist "$artist")
        local album=$(select_from "$albums\n$all" "album")

        if [ "$album" = "$all" ]; then
            $MPC findadd Artist "$artist"
        elif [ -n "$album" ]; then
            local songs=$($MPC list Title Album "$album")
            local song=$(select_from "$songs\n$all" "song")

            if [ "$song" = "$all" ]; then
                $MPC findadd Album "$album"
            elif [ -n "$song" ]; then
                $MPC findadd Title "$song"
            fi
        fi
    fi
}

save() {
    $MPC save $(dmenu -b -p "Save Playlist As:")
}

remove() {
    local playlist=$(get_playlist)
    local song=$(select_from "$playlist" "song")

    [ -n "$song" ] && $MPC del "${song%%\ *}"
}

jump() {
    local playlist=$(get_playlist)
    local song=$(select_from "$playlist" "song")

    [ -n "$song" ] && $MPC play "${song%%\ *}"
}

playpause() {
    $MPC toggle
}

randtoggle() {
    $MPC random
}

# if shuffle is on, the command "shuffle off" should be available;
# otherwise the command "shuffle on" instead
if mpc | grep "random: on" >/dev/null; then
    SHUFFLE="Shuffle OFF"
else
    SHUFFLE="Shuffle ON"
fi

# if playing, show "pause"; else show "play"
if mpc | grep "playing" >/dev/null; then
    PLAY="Pause"
else
    PLAY="Play"
fi

while true; do
    action=$(DMENU "$PLAY\nJump\nNext\n$SHUFFLE\nClear\nAdd\nRemove\nSave\n")
    case $action in
        Jump     ) jump;;
        $PLAY    ) playpause;;
        Next     ) $MPC next;;
        $SHUFFLE ) randtoggle;;
        Clear    ) $MPC clear;;
        Add      ) add;;
        Remove   ) remove;;
        Save     ) save;;
        ""       ) exit 0;;
    esac
done
